---
apiVersion: v1
kind: Namespace
metadata:
  name: catalog
apiVersion: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: catalog
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: redis
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      labels:
        deployment: redis
    spec:
      containers:
      - env:
        - name: REDIS_PASSWORD
          value: redhat
        image: quay.io/redhattraining/redis:6.2
        imagePullPolicy: IfNotPresent
        name: redis
        ports:
        - containerPort: 6379
          protocol: TCP
        resources:
          limits:
            cpu: 32m
            memory: 10Mi
          requests:
            cpu: 32m
            memory: 10Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: redis-volume-1
      nodeSelector:
        base: alpha
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: redis-volume-1
