apiVersion: v1
kind: Namespace
metadata:
  name: 
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: <name>
  namespace: <name>
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: <name>-operator
  namespace: <name>
spec:
  channel: stable
  installPlanApproval: Automatic | Manual
  source: do380-catalog
  sourceNamespace: <name>
  name: <name>-operator
...
