apiVersion: v1
kind: PersistentVolume
metadata:
  name: lamda-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /exports-ocp4
    server: 192.168.50.254
  persistentVolumeReclaimPolicy: Delete
  claimRef:
    name: lamdapvc
    namespace: galaxy
